### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by katebogolepova** [TimberToss/School-Diary#1]
1. Порадовало то, что попробовал котлин, а также то, что постарался разделить код на пакеты по функциональности.
2. Используй константы, например вот тут вместо "rings" и "serialNumber": val query = firestore.collection("rings")
                .orderBy("serialNumber") 
3. Тексты ошибок лучше тоже помещать в ресурсы.
4. Почему в манифесте нет никаких разрешений? Как обрабатывается отсутствие интернета?
5. Приложение получилось слишком "информационным" (просто вывод какой-то информации на экран), хотелось бы добавить побольше интерактива, например, чтобы ученик мог общаться с друзьями или с учителем, добавлять комментарии, получать уведомления об изменениях в расписании занятий.
6. Идея хорошая, можно потом выложить в плей маркет, если доработать. Особенно сейчас актуально)))

**Comment by TimberToss** [comment]
@katebogolepova При отсутствии интернета данные будут браться из заранее скачанных данных, т.к. Firebase предоставляет  кэширование из коробки. А permission запамятовал добавить, т.к. тестировал приложение только на эмуляторе, но, в любом случае, это глупая ошибка с моей стороны

**Comment by TimberToss** [comment]
@katebogolepova сделал hotfix с заменой строк на константы, добавил тексты ошибок в ресурсы, а также дописал permission на использование интернета в манифест
